### ISSUE TITLE
ValueError: Element locator 'xpath=//a[@data-menu='Sales']' did not match any elements.

### ISSUE THREAD

**Issue by max3903** [brain-tec/odoo-robot-framework#25]
Hello,

I am using odoo_9_0_EE.robot to run some basic tests with Odoo 9:
https://github.com/kmee/odoo-robot-framework/pull/3

I am stuck at the error below:

```
$ pybot -v CONFIG:config.py test.robot 
==============================================================================
Test :: Full workflow demonstration                                           
==============================================================================
Valid Login                                                           | PASS |
------------------------------------------------------------------------------
Create Sale Order                                                     | FAIL |
ValueError: Element locator 'xpath=//a[@data-menu='Sales']' did not match any elements.
------------------------------------------------------------------------------
Process Sale Order                                                    | FAIL |
Element 'xpath=//div[contains(@class,'o_cp_pager')]' did not appear in 20 seconds
------------------------------------------------------------------------------
Process Delivery Order                                                | FAIL |
Element 'xpath=//div[contains(@class,'o_cp_pager')]' did not appear in 20 seconds
------------------------------------------------------------------------------
Invoice Delivery Order                                                ^CSecond signal will force exit.
[ WARN ] Keyword 'Capture Page Screenshot' could not be run on failure: Execution terminated by signal
Invoice Delivery Order                                                | FAIL |
Execution terminated by signal
------------------------------------------------------------------------------
Test :: Full workflow demonstration                                   | FAIL |
5 critical tests, 1 passed, 4 failed
5 tests total, 1 passed, 4 failed
==============================================================================
Output:  /home/mchambreuil/git/odoo-robot-framework/output.xml
Log:     /home/mchambreuil/git/odoo-robot-framework/log.html
Report:  /home/mchambreuil/git/odoo-robot-framework/report.html
```

Odoo is putting a number as the id, not the menuitem name.

**Comment by BT-astauder** [comment]
Hello @max3903 

Without the actual robot test it's hard to guess what you tried to execute. Could you post this please?

Regards
Andreas

**Comment by max3903** [comment]
Hi @BT-astauder 

Here is the robot file:
https://github.com/max3903/odoo-robot-framework/blob/master/sale_stock_invoice_workflow.robot

Just replace the resource to use `odoo_9_0_EE.robot`

**Comment by mileo** [comment]
@max3903 Whats is the version/repo/branch of web_selenium odoo addon?

**Comment by max3903** [comment]
@mileo I am not using web_selenium. Where is this module?

**Comment by mileo** [comment]
In my test https://github.com/kmee/odoo-travis-robotframework/blob/master/common.cfg#L27
But you can use: https://github.com/brain-tec/web_selenium

This module insert attributes on html:

![captura de tela de 2016-10-19 17-15-35](https://cloud.githubusercontent.com/assets/1975978/19533715/b2a4835a-961f-11e6-801b-b342c6898bea.png)

**Comment by max3903** [comment]
Aaahhh... got it :D

**Comment by mileo** [comment]
Now is working: https://travis-ci.org/kmee/odoo-travis-robotframework#L3381

But i still have to check properties in lines, to enable sale item popup.

**Comment by max3903** [comment]
@mileo I did install the web_selenium module on version 9. I still get numbers for my Sales menu:

```
data-bt-testing-sub-menu_id="67"
```

and I don't get anything for the icon of the home page of the enterprise:

```
<a class="o_app o_action_app" data-action-id="145" data-action-model="ir.actions.act_window" data-menu="63" href="#menu_id=63&amp;action_id=145">
            <img class="o_app_icon" src="[...]">
            <div class="o_caption">Sales</div>
          </a>
```

**Comment by max3903** [comment]
@mileo I think I found my bug:
https://github.com/brain-tec/web_selenium/issues/9

**Comment by mileo** [comment]
Nice! Sorry that i can help you in time. this is a nice tool, tel me if you had time to see the sphinix integration
